### ISSUE TITLE
geoclue not removed with kicksecure-cli-host

### ISSUE THREAD

**Issue by ghost** [Kicksecure/developer-meta-files#3]
Just installed `kicksecure-cli-host` on a debian based distro.
I was looking to see if geoclue was removed but in fact it wasn't?

```console
[user]~$ apt list --installed |grep geoclue

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

geoclue-2.0/bookworm,now 2.6.0-2 amd64 [installed,automatic]
libgeoclue-2-0/bookworm,now 2.6.0-2 amd64 [installed,automatic]
```

and `cat /etc/group` shows geoclue in group

Anyway I was under the impression that kicksecure-cli-host modifies it the same way as normal debian morphing except for modyfing the desktop environment. I'm not a huge fan of xfce and have previously morphed debian 12 boomworm and wanted the same thing minus the xfce environment.

Please make geoclue automatically removed with kicksecure-cli-host package
and remove the geoclue group also

```
usermod -g user geoclue
groupdel geoclue
```

**Comment by adrelanos** [comment]
> Anyway I was under the impression that kicksecure-cli-host modifies it the same way as normal debian morphing except for modyfing the desktop environment.

Double wrong impression. No matter if CLI or GUI package...

There is no "package hostility automatic removal feature" or however such a feature would be called.

I don't know how the impression was created that such a feature exists?

> Please make geoclue automatically removed with kicksecure-cli-host package and remove the geoclue group also

This isn't easy.

A Kicksecure meta package could add `Conflicts: geoclue-2.0`. APT would tell the user then, that (potentially whole of GNOME) is going to be removed before installing the meta package. If not reading that and proceeding, the desktop environment would be broken.

Another option would be implementing a dummy package which `Provides: geoclue-2.0` but that might cause other bugs in the packages which `Depends: geoclue-2.0`.

This is also the wrong repository and the wrong place for Kicksecure feature requests. Hence, closing.

related:
https://github.com/Whonix/anon-meta-packages/commit/d9c96fcda6e8dd8ed147d57c71843e003d898d47

**Comment by adrelanos** [comment]
https://forums.whonix.org/t/expand-systemcheck-unwanted-packages-list/2155/26

**Comment by ghost** [comment]
>I don't know how the impression was created that such a feature exists?

> https://www.kicksecure.com/wiki/Privacy
>> Furthermore, problematic software like GeoClue is excluded due to privacy concerns associated with GeoClue

>that (potentially whole of GNOME) is going to be removed before installing the meta package.

I do know exactly what your talking about as I installed Debian 12 with GNOME in a VM and purged `geoclue-2.0` `gir1.2-geoclue-2.0` `libgeoclue-2-0` which uninstalled `gnome-core` lol

I tried again by just removing `geoclue-2.0` and it doesn't remove `gnome-core`.
However removing `gir1.2-geoclue-2.0` and `libgeoclue-2-0` will break GNOME.
Furthermore TailsOS removes ONLY `geoclue-2.0` as that is only package required for geoclue tracking to even work.\
 This doesn't break GNOME which tails is built on.

Anyway sorry to open this issue here I didn't know right place.
